

NETWORK_PROFILES = 'wifi.dat'
CONF_FILE = 'conf.dat'
SENSOR_FILE = 'sensor.dat'

DEFAULT_HOST_IP = '10.0.0.4'
DEFAULT_MQTT_SUB_TOPIC = 'RoomSensorik'
DEFAULT_MQTT_PUB_TOPIC = 'HA'

SSID = "RoomSensorik"
PASSWORD = "RoomSensorik"
AUTHMODE = 3  # WPA2
NETWORK_PROFILES = 'wifi.dat'

PIN_SCL = 22
PIN_SDA = 21

SENSORS_SLEEP = 10